version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: .config/php/Dockerfile
    image: salvio/php-composer-dev
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./code:/var/www/html
      - .config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - .config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - myproject-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myproject
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - data-mysql:/var/lib/mysql
      - .config/mysql/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - myproject-network

  #REDIS Service
  redis:
    image: redis:latest
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: redis
    volumes:
      - ./.config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - myproject-network

    #MAILCATCHER Service
  mailcatcher:
    build:
      context: .
      dockerfile: .config/mailcatcher/Dockerfile
    image: salvio/mailcatcher-dev
    restart: unless-stopped
    tty: true
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mailcatcher
    networks:
      - myproject-network

#Docker Networks
networks:
  myproject-network:
    driver: bridge

#MYSQL DATA volume
volumes:
  data-mysql:
    driver: local
